INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Sinclair', '32', 'male', 'yes', 'yes', '4', '4', '4', 'yes', 'Message from Sinclair!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Shalieka', '28', 'female', 'yes', 'yes', '4', '4', '4', 'yes', 'Message from Shalieka!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Derek', '40', 'male', 'no', 'yes', '3', '3', '3', 'no', 'Message from Derek!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Jeff', '32', 'male', 'no', 'yes', '3', '4', '3', 'no', 'Message from Jeff!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Daniella', '30', 'female', 'yes', 'yes', '4', '3', '4', 'yes', 'Message from Daniella!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Sinead', '29', 'female', 'yes', 'no', '4', '4', '4', 'yes', 'Message from Sinead!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Cynthia', '42', 'female', 'yes', 'yes', '5', '5', '5', 'yes', 'Message from Cynthia!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Sandra', '45', 'female', 'yes', 'yes', '3', '4', '2', 'no', 'Message from Sandra!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Stella', '39', 'female', 'yes', 'no', '3', '3', '3', 'no', 'Message from Stella!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Chris', '28', 'male', 'no', 'yes', '4', '5', '3', 'yes', 'Message from Chris!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Michael', '28', 'male', 'yes', 'yes', '4', '5', '4', 'no', 'Message from Michael!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Kofi', '26', 'male', 'yes', 'no', '5', '5', '4', 'no', 'Message from Kofi!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Leslie', '35', 'male', 'yes', 'yes', '5', '4', '4', 'no', 'Message from Leslie!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Edna', '34', 'female', 'no', 'yes', '4', '4', '3', 'yes', 'Message from Edna!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Vivian', '40', 'female', 'yes', 'yes', '5', '5', '4', 'yes', 'Message from Vivian!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Angela', '41', 'female', 'yes', 'no', '4', '3', '2', 'yes', 'Message from Angela!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Kofi', '30', 'male', 'no', 'yes', '4', '5', '4', 'yes', 'Message from Kofi!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Wayne', '32', 'male', 'no', 'yes', '4', '4', '4', 'yes', 'Message from Wayne!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Chris', '35', 'male', 'no', 'yes', '4', '4', '4', 'no', 'Message from Chris!', 'someone@someone.com', '2019-09-22');
INSERT INTO aurous_feedback (name, age, sex, first_visit, return_visit, cleanliness, customer_service, speed, shisha, comment, email, date_stamp)
VALUES ('Danny', '28', 'male', 'no', 'yes', '4', '4', '4', 'no', 'Message from Danny!', 'someone@someone.com', '2018-09-22');